### ISSUE TITLE
User should be free to choose how they receive the feedback

### ISSUE THREAD

**Issue by Chrislock1** [equinor/it-compliance-action#4]
User should be able to configure if the bot writes a comment in the PR or if it creates new issues, or something else. 

Example workflow file

```yaml
# .github/workflows/compliance.yml

on: [push]
jobs: 
  compliance_test:
    runs-on: ubuntu-latest
    name: Compliance test
    permissions:
      issues:   write
      contents: read
    steps:
      - name: Checkout # Makes the source code available to be scanned
        id:   checkout
        uses: actions/checkout@v4 
      - name: Scan repo # Scans the source code and repo for compliance
        id:   scan
        uses: equinor/it-compliance-action@v0.2.1-alpha
        with:
          output: issue # issue|comment|webhook   <------------ NEW FEATURE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
